# Generated by Django 5.2 on 2025-04-26 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_customuser_already_voted_votingresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='already_voted',
        ),
    ]
