# Generated by Django 5.2 on 2025-04-26 18:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_customuser_already_voted'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='voters',
            field=models.ManyToManyField(blank=True, related_name='voted_elections', to=settings.AUTH_USER_MODEL),
        ),
    ]
